# .github/workflows/build-unsigned-ipa.yml
name: Build unsigned .ipa

on:
  workflow_dispatch:
    inputs:
      scheme:
        description: 'Xcode scheme to build'
        required: true
        default: 'App'
      configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'
      sdk:
        description: 'SDK to build against'
        required: false
        default: 'iphoneos'
      export_name:
        description: 'Filename to use for produced .ipa (without extension)'
        required: false
        default: 'UnsignedApp'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build .app without code signing
        run: |
          set -euo pipefail
          xcodebuild \
            -scheme "${{ github.event.inputs.scheme }}" \
            -configuration "${{ github.event.inputs.configuration }}" \
            -sdk "${{ github.event.inputs.sdk }}" \
            BUILD_DIR="$(pwd)/build" \
            clean build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Find .app
        id: find_app
        run: |
          APP_PATH="$(find "$(pwd)/build" -type d -name "*.app" -print -quit || true)"
          if [ -z "$APP_PATH" ]; then
            echo "::error ::.app not found"
            exit 1
          fi
          echo "APP_PATH=$APP_PATH" >> "$GITHUB_OUTPUT"

      - name: Package unsigned .ipa
        run: |
          APP_PATH="${{ steps.find_app.outputs.APP_PATH }}"
          IPA_NAME="${{ github.event.inputs.export_name }}.ipa"
          TMPDIR="$(mktemp -d)"
          mkdir -p "$TMPDIR/Payload"
          cp -a "$APP_PATH" "$TMPDIR/Payload/"
          (cd "$TMPDIR" && zip -qry "$IPA_NAME" Payload)
          mkdir -p artifacts
          mv "$TMPDIR/$IPA_NAME" artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: artifacts/*.ipa
